sudo: required
services:
  - docker

before_install:
  - docker build -t locvt/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run locvt/react-test npm test -- --coverage

after_success:
  - docker build -t locvt/multi-client ./client
  - docker build -t locvt/multi-nginx ./nginx
  - docker build -t locvt/multi-server ./server
  - docker build -t locvt/multi-worker ./worker

# Login to the docker CLI ( with setting travis setting environment DOCKER_ID and DOCKER_PASSWORD )
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to the docker hub
  - docker push locvt/multi-client
  - docker push locvt/multi-nginx
  - docker push locvt/multi-client
  - docker push locvt/multi-worker
